[package]
name = "xpath"
version = "0.1.4"
authors = ["Timothy <2779546+Its-its@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.4"

html5ever = "0.25.1"
markup5ever = "0.10.0"
markup5ever_rcdom  = "0.1.0"


